In [1]:
cd C:\Users\venka\OneDrive\Desktop\Driven Data

C:\Users\venka\OneDrive\Desktop\Driven Data


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv('train_values.csv')
X_train = dataset.iloc[:, 1:].values

In [4]:
X_train[1,:]

array([8, 900, 2812, 2, 10, 8, 7, 'o', 'r', 'n', 'x', 'q', 's', 'd', 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 'v', 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=object)

In [5]:
dataset1=pd.read_csv('train_labels.csv')
y_train = dataset1.iloc[:, 1].values

In [6]:
y_train

array([3, 2, 3, ..., 3, 2, 3], dtype=int64)

In [7]:
dataset=pd.read_csv('test_values.csv')
X_test = dataset.iloc[:, 1:].values

In [8]:
building_id = dataset.iloc[:, 0].values

In [9]:
columns=[0,1,2,3,4,5,6]

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :7] = sc.fit_transform(X_train[:, :7])
X_test[:, :7] = sc.transform(X_test[:, :7])

In [11]:
X_test[1,:]

array([-0.9834136903330413, -1.3570661339594738, 1.5711887171651733,
       -0.17827372029010577, -0.020866064690527514, 1.1342661732138557,
       -0.2264188317477409, 't', 'r', 'n', 'f', 'q', 's', 'd', 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 'v', 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=object)

In [12]:
columns=[7,8,9,10,11,12,13,25]

In [13]:
X_train[0,columns]

array(['t', 'r', 'n', 'f', 'q', 't', 'd', 'v'], dtype=object)

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), columns)], remainder='passthrough')
X_train = np.array(ct.fit_transform(X_train))
X_test = np.array(ct.fit_transform(X_test))

In [15]:
from sklearn.ensemble import RandomForestClassifier
classifierRFC = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifierRFC.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [16]:
from sklearn.tree import DecisionTreeClassifier
classifierDTC = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierDTC.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [29]:
from lightgbm import LGBMClassifier
ClassifierLGBM = LGBMClassifier(num_leaves=200,objective='multiclass',n_estimators=150,random_state=10)
ClassifierLGBM.fit(X_train, y_train)

LGBMClassifier(n_estimators=150, num_leaves=200, objective='multiclass',
               random_state=10)

In [18]:
from xgboost import XGBClassifier
classifierXGB=XGBClassifier()
classifierXGB.fit(X_train,y_train)

C:\Users\venka\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[01:30:09] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [19]:
y_pred_RFC =classifierRFC.predict(X_test)
y_pred_DTC=classifierDTC.predict(X_test)
y_pred_LGBM=ClassifierLGBM.predict(X_test)
y_pred_XGB=classifierXGB.predict(X_test)

In [25]:
dict_RFC={'building_id':building_id,'damage_grade':y_pred_RFC}
df_RFC=pd.DataFrame(dict_RFC)
df_RFC.to_csv('RFC1.csv',index=False)

In [26]:
dict_DTC={'building_id':building_id,'damage_grade':y_pred_DTC}
df_DTC=pd.DataFrame(dict_DTC)
df_DTC.to_csv('DTCC1.csv',index=False)

In [30]:
dict_LGBM={'building_id':building_id,'damage_grade':y_pred_LGBM}
df_LGBM=pd.DataFrame(dict_LGBM)
df_LGBM.to_csv('LGBM2.csv',index=False)

In [28]:
dict_XGB={'building_id':building_id,'damage_grade':y_pred_XGB}
df_XGB=pd.DataFrame(dict_XGB)
df_XGB.to_csv('XGB1.csv',index=False)